Fix ssh key type to supported one
```
Error: Failed to apply catalog: Parameter type failed on Ssh_authorized_key[zack
zack@noziere]: Invalid value "no-touch-required sk-ssh-ed25519@openssh.com". Valid
values are ssh-dss, ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384,
ecdsa-sha2-nistp521, ssh-ed25519. (file:
/etc/puppet/code/environments/production/site-modules/profile/manifests/ssh/server.pp,
line: 37)
```

bin/octo is happy:

```
diff origin/production/thyssen.internal.softwareheritage.org current/thyssen.internal.softwareheritage.org
*******************************************
  Ssh_authorized_key[zack zack@noziere2] =>
   parameters =>
     type =>
      - no-touch-required sk-ssh-ed25519@openssh.com
      + ssh-ed25519
*******************************************
  Ssh_authorized_key[zack zack@noziere] =>
   parameters =>
     type =>
      - no-touch-required sk-ssh-ed25519@openssh.com
      + ssh-ed25519
*******************************************
*** End octocatalog-diff on thyssen.internal.softwareheritage.org
```

Refs. swh/infra/sysadm-environment#4770