rancher-node-highmem04: Stop zpool configuration through puppet
After the manual change from mirrored zpool to 'inline' zpool, it's not too
happy with the new organization (when inlining the disks).

The noop [1] was happy with previous content but actually fails at runtime [2].

[1]
```
Notice: /Stage[main]/Profile::Zfs::Common/Zpool[data]/disk: current_value
['nvme-MO006400KXPAB_240747ABFC6C nvme-MO006400KXPAB_240747ABFC7A
nvme-MO006400KXPAB_240747ABFC8C nvme-MO006400KXPAB_240747ABFCB0
nvme-MO006400KXPAB_240747ABFCDB nvme-MO006400KXPAB_240747ABFD26
nvme-MO006400KXPAB_240747ABFC75 nvme-MO006400KXPAB_240747ABFC82
nvme-MO006400KXPAB_240747ABFC96 nvme-MO006400KXPAB_240747ABFCD8
nvme-MO006400KXPAB_240747ABFD23 nvme-MO006400KXPAB_240747ABFD3C'], should be
['/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC6C',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC7A',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC8C',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCB0',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCDB',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD26',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC75',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC82',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC96',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCD8',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD23',
'/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD3C'] (noop)
```

[2]
```
Error: zpool disk can't be changed. should be ["/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC6C", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC7A", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC8C", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCB0", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCDB", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD26", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC75", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC82", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC96", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCD8", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD23", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD3C"], currently is ["nvme-MO006400KXPAB_240747ABFC6C nvme-MO006400KXPAB_240747ABFC7A nvme-MO006400KXPAB_240747ABFC8C nvme-MO006400KXPAB_240747ABFCB0 nvme-MO006400KXPAB_240747ABFCDB nvme-MO006400KXPAB_240747ABFD26 nvme-MO006400KXPAB_240747ABFC75 nvme-MO006400KXPAB_240747ABFC82 nvme-MO006400KXPAB_240747ABFC96 nvme-MO006400KXPAB_240747ABFCD8 nvme-MO006400KXPAB_240747ABFD23 nvme-MO006400KXPAB_240747ABFD3C"]
Error: /Stage[main]/Profile::Zfs::Common/Zpool[data]/disk: change from ['nvme-MO006400KXPAB_240747ABFC6C nvme-MO006400KXPAB_240747ABFC7A nvme-MO006400KXPAB_240747ABFC8C nvme-MO006400KXPAB_240747ABFCB0 nvme-MO006400KXPAB_240747ABFCDB nvme-MO006400KXPAB_240747ABFD26 nvme-MO006400KXPAB_240747ABFC75 nvme-MO006400KXPAB_240747ABFC82 nvme-MO006400KXPAB_240747ABFC96 nvme-MO006400KXPAB_240747ABFCD8 nvme-MO006400KXPAB_240747ABFD23 nvme-MO006400KXPAB_240747ABFD3C'] to ['/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC6C', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC7A', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC8C', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCB0', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCDB', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD26', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC75', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC82', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC96', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCD8', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD23', '/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD3C'] failed: zpool disk can't be changed. should be ["/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC6C", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC7A", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC8C", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCB0", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCDB", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD26", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC75", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC82", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFC96", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFCD8", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD23", "/dev/disk/by-id/nvme-MO006400KXPAB_240747ABFD3C"], currently is ["nvme-MO006400KXPAB_240747ABFC6C nvme-MO006400KXPAB_240747ABFC7A nvme-MO006400KXPAB_240747ABFC8C nvme-MO006400KXPAB_240747ABFCB0 nvme-MO006400KXPAB_240747ABFCDB nvme-MO006400KXPAB_240747ABFD26 nvme-MO006400KXPAB_240747ABFC75 nvme-MO006400KXPAB_240747ABFC82 nvme-MO006400KXPAB_240747ABFC96 nvme-MO006400KXPAB_240747ABFCD8 nvme-MO006400KXPAB_240747ABFD23 nvme-MO006400KXPAB_240747ABFD3C"]
```

Refs. swh/infra/sysadm-environment#5754#note_229089