data/common/common.yaml: Fix puppet type error for apache instance
Detected the error [1] while adapting the inventory CNAME for netbox.

This changes the current configuration from 15 to 1 on pergamon machine.
The documentation on the puppet module does not explicit the unit. I'm
assuming it's seconds.

[1]
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Apache]: parameter 'keepalive_timeout' expects an Integer v
alue, got String (file: /etc/puppet/code/environments/production/site-modules/profile/manifests/apache/common.pp, line: 2, column: 3) on node pergamon.softwareheritage.org
```

[2]
```
-KeepAliveTimeout 15
+KeepAliveTimeout 1
```

Refs. swh/infra/sysadm-environment#5777